apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  lables:
    app: pgadmin
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
