apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    group: db
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
